Prevent trailing white spaces in asset names #1510
OHDSI/WebAPI pull request #1632
Opened 2020-09-21 13:21 UTC by anton-abushkevich

resolves #1510

2020-09-21 13:24 UTC, wivern requested changes

2020-09-21 13:24 UTC, wivern commented on src/main/java/org/ohdsi/webapi/cohortcharacterization/converter/BaseCcDTOToCcEntityConverter.java
> +    cohortCharacterization.setName(source.getName().trim());
Why not to use smth like `StringUtils.trim` to prevent unexpected NPE?

2020-09-22 09:30 UTC, anton-abushkevich commented on src/main/java/org/ohdsi/webapi/cohortcharacterization/converter/BaseCcDTOToCcEntityConverter.java
> +    cohortCharacterization.setName(source.getName().trim());
Fixed.

2020-09-23 03:37 UTC, chrisknoll approved these changes

2020-09-24 10:35 UTC, wivern approved these changes

2020-09-24 10:35 UTC, merged