getCurrentUser must be called before any update/delete operations()
OHDSI/WebAPI pull request #1667
Opened 2020-10-29 06:42 UTC by ssuvorov-fls

2020-11-02 18:19 UTC, anton-abushkevich commented
It works, but:
1. Open a source, uncheck daimon (for example, "temp"), save
2. Open the source, create same daimon again, save
3. Repeat 1 and 2 several times

Now check the database table "source_daimon" - there will be all created and deleted daimons with priority set to "-1". Question: may be it will be cleaner to reuse existing deleted daimon, when creating a new one? I.e. check if we already have a daimon in the source with daimon_type and if we do - then update its name and priority, not creating a new one.

2020-11-02 18:30 UTC, anton-abushkevich commented
Also:

if multiple daimons with the same type is not allowed for one source, then it would be appropriate to add a unique constraint on two column: `UNIQUE (source_id, daimon_type)`.

2020-11-02 19:19 UTC, chrisknoll commented
I think maybe a reason to not reuse is that it will also reuse the source_id value, which may then accidently associate results (ie: generation results) to a given source_id.

Maybe a solution is to set the source_key to NULL if you do a soft delete?

2020-11-09 12:56 UTC, anton-abushkevich requested changes

2020-11-09 12:56 UTC, anton-abushkevich commented on src/main/resources/db/migration/postgresql/V2.8.0.20201103171300__add_source_daimon_unique_constraint.sql
> +ALTER TABLE ${ohdsiSchema}.source_daimon ADD CONSTRAINT un_source_daimon UNIQUE (source_id,daimon_type);
Migration fails, if the table already has dublicates. First, have to delete those with priority = -1.

2020-11-11 13:10 UTC, anton-abushkevich approved these changes

2020-11-11 13:10 UTC, merged

2020-11-13 14:31 UTC, chrisknoll commented
This migration failed on SqlServer:

SQL State  : S0001
Error Code : 102
Message    : Incorrect syntax near 'sd1'.
Location   : db/migration/sqlserver/V2.8.0.20201103171300__add_source_daimon_unique_constraint.sql (C:\Git\WebAPI\target\classes\db\migration\sqlserver\V2.8.0.20201103171300__add_source_daimon_unique_constraint.sql)

2020-11-13 16:38 UTC, ssuvorov-fls commented
@chrisknoll Thanks a lot and sorry for mistake