GitHub actions
OHDSI/WebAPI pull request #1690
Opened 2020-11-18 15:28 UTC by blootsvoets

Enabled GitHub actions. It requires repository secrets
```
DOCKER_HUB_USERNAME
DOCKER_HUB_ACCESS_TOKEN
```
to be set.

Changes to the POM file:
- The repositories have been slightly reordered to allow faster dependency fetching when there is no cache. 
- The miredot plugin is disabled inside docker since the result is not used there
- The git-commit-id-plugin is disabled and instead is provided as part of the GitHub action.
- Java 11 is used for docker compilation, since Java 8 is not used during runtime and the miredot plugin is the only plugin not compatible with Java 11.
- Updated the war plugin, since the old version generated warnings on Java 11.

2020-11-18 15:51 UTC, blootsvoets commented
Tagging @leeevans and @anthonysena for their earlier review of the Dockerfile integration.

2021-01-19 16:54 UTC, leeevans commented
@blootsvoets 
Please update this pull request to handle the pom.xml conflict and I will go ahead and merge.

I've setup the GitHub repo secrets for this WebAPI & the Atlas repo and created the Docker Hub access token (thanks @msuchard for your help)

2021-01-19 17:17 UTC, leeevans reviewed
@blootsvoets is there an easy way for folks to distinguish the Docker Hub CI build docker image from the Release build docker image? If not, should we use 'ohdsi/webapi-snapshot' for the CI build docker image name?

2021-01-26 16:33 UTC, blootsvoets commented
Thanks @leeevans. I've merged the master branch. Note that I did add back the maven central repo to the `pom.xml`, because this decreases the war build time from 3:46 to 1:26 minutes, making it 2.6 times faster to build this way.

Snapshots are differentiated from releases by their tag. Releases have a tag that matches the Github Release, for example `2.8.0` and every new release will replace the `latest` tag. Commits to master get the `master` tag, whereas pull requests to master get the `pr-<github-pr-number>` tag.

2021-01-26 19:39 UTC, leeevans approved these changes
@blootsvoets thanks for updating with latest pom.xml file and answering my question about snapshot tracking.

2021-01-26 22:14 UTC, anthonysena requested changes

2021-01-26 22:14 UTC, anthonysena commented on pom.xml
> +      <url>https://repo.maven.apache.org/maven2</url>
Tagging @chrisknoll @leeevans - I was going to merge this set of changes in and noticed the addition of this repository. Isn't it now the case that any/all requests for dependencies will go to `repo.ohdsi.org`'s nexus and when not found there, it will source them (presumably through maven central) and therefore this `<repository>` reference is no longer required?

2021-01-26 22:16 UTC, anthonysena commented on pom.xml
> +      <url>https://repo.maven.apache.org/maven2</url>
Sorry, I should have re-read the PR. @blootsvoets mentioned:

> Note that I did add back the maven central repo to the pom.xml, because this decreases the war build time from 3:46 to 1:26 minutes, making it 2.6 times faster to build this way.

Let me know if you have any concerns w/ this otherwise I'm fine to merge in these changes. Thanks!

2021-01-27 00:03 UTC, chrisknoll commented on pom.xml
> +      <url>https://repo.maven.apache.org/maven2</url>
No we should use the ohdsdi.org repo since that bridges all the repos to a single endpoint, and will be even faster than just putting central first (since it will go through central connection first then to ohdsi), but with the updated repositories element, it only needs to go to ohdsi maven and it will have all the maven artifacts cached.

For refrence, this is the only thing we need in pom:
```
  <repositories>
    <repository>
      <id>ohdsi</id>
      <name>repo.ohdsi.org</name>
      <url>http://repo.ohdsi.org:8085/nexus/content/groups/public</url>
    </repository>
  </repositories>
```

2021-01-27 10:52 UTC, blootsvoets commented on pom.xml
> +      <url>https://repo.maven.apache.org/maven2</url>
Maven central uses a large CDN, so data is always stored relatively close to the person doing the build, and they have invested in fast networks and hardware to give the fastest possible response. This can empirically be verified by doing the docker build with and without central as first element, since this build cannot use the maven cache. It will also be the case for new contributors that do not yet have the dependencies cached yet. In terms of cost. So while indeed you don’t _need_ central as the first repository, it does save time, costs and energy.

If you still prefer it to be removed, let me know and I’ll do it ASAP.

2021-01-27 10:58 UTC, blootsvoets commented
An unrelated question about repo.ohdsi.org: would it be possible to use HTTPS there, for example using letsencrypt? Gradle has already phased out support for non-HTTPS maven repositories mainly to guard against man in the middle attacks: https://blog.gradle.org/decommissioning-http
Maven central has discontinued HTTP support in the beginning of 2020.

2021-01-27 15:11 UTC, chrisknoll commented on pom.xml
> +      <url>https://repo.maven.apache.org/maven2</url>
That's an interesting point about the CDN, but I'm not sure it will make a big difference in practice.  According to [this reference from Apache](https://maven.apache.org/repository-management.html), it is a best practice to use a repository manager with a proxy to the public maven repositories, and they call out the build performance when dealing with snapshots.  But, I think you can also set up your own local settings.xml file to reference your own preferred maven repositories, [described in this stack overflow post](https://stackoverflow.com/questions/5325407/how-to-set-order-of-repositories-in-maven-settings-xml).

I want to be accomodating, but we've gone through a few iterations on configuring repositories in the pom.xml and using central.  The biggest impact I've seen is that when doing local builds during development (and we're referencing snapshots) each build wants to make sure latest snapshot is available, and it would go out to a number of other repositories before finally getting to the ohdsi.org's repo and finding out that nothing has changed. This added at least 30-60 seconds to the build, which when you're doing multiple builds per hour, it really adds up.  I haven't checked if we put central + ohdsi nexus into the pom if it leads to a slower build time...but using the single ohdsi nexus seems to be working ok.

So, did you want to try to see if using a pom.xml with central  vs. without using it to determine if it has any impact on your docker build times?  Also see if you can configure your own settings.xml to add central to it to see if you get the desired result of accessing central first before ohdsi nexus?  If you are still experiencing problems even after using the ohdsi group `http://repo.ohdsi.org:8085/nexus/content/groups/public`, I'll check to see if adding the central to the pom.xml impacts build times.

2021-01-27 15:12 UTC, chrisknoll commented
@leeevans maintains the host, and so I think he'd be the best to answer if he can set up an SSL cert and enable HTTPS on the server. I agree, we should be using SSL, but am also sensitive to the maintenance burden this could be put on @leeevans .

2021-01-27 20:23 UTC, leeevans commented
@blootsvoets yes, I will be moving repo.ohdsi.org to HTTPS in the next couple of weeks. I'll coordinate with @anthonysena and @chrisknoll so the repo reference in the pom.xml can be updated at the appropriate time

2021-01-28 07:53 UTC, blootsvoets commented on pom.xml
> +      <url>https://repo.maven.apache.org/maven2</url>
Alright, yes I did try the difference. I've now committed a change where the central repo is only used in the docker build. Would that alleviate your concerns? As mentioned in the first post, using central as a first repository reduces the WAR build time from 3:46 to 1:26.

2021-01-28 13:26 UTC, chrisknoll commented on pom.xml
> +      <url>https://repo.maven.apache.org/maven2</url>
Yes, that works for me. Thanks.

2021-02-02 16:26 UTC, blootsvoets commented
The POM has been modified as requested. @anthonysena or @chrisknoll would you please take another look?

2021-02-02 16:57 UTC, chrisknoll commented
Looks good.

2021-02-02 17:00 UTC, anthonysena approved these changes

2021-02-02 17:00 UTC, merged