Fixed calculation for standard mean difference.
OHDSI/WebAPI pull request #1813
Opened 2021-03-09 06:48 UTC by chrisknoll

Fixes #1812.

2021-04-06 14:14 UTC, anthonysena requested changes
Noted some differences in the calc when comparing to:

https://github.com/OHDSI/FeatureExtraction/blob/develop/R/CompareCohorts.R#L75-L82

2021-04-06 14:14 UTC, anthonysena commented on src/main/java/org/ohdsi/webapi/cohortcharacterization/report/PrevalenceItem.java
> +      double pooledPrevalence = (pTreatment * (1.0 - pTreatment)) + (pCompare * (1.0 - pCompare));
I think the idea with `pooledPrevalence` is to compute the overall SD? That should take the form:

`SD_overall = SQRT((SD_t ^2 + SD_c^2) / 2)`

2021-04-06 14:14 UTC, anthonysena commented on src/main/java/org/ohdsi/webapi/cohortcharacterization/report/PrevalenceItem.java
> +        return (pTreatment - pCompare) / Math.sqrt((pooledPrevalence / 2));
Assuming you revise `pooledPrevalence` as noted above, then this return should be revised to:

`return = (pCompare - pTreatment) / pooledPrevalence;`

Note the change in the numerator to `pCompare - pTreatment`

2021-04-06 16:27 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/cohortcharacterization/report/PrevalenceItem.java
> +        return (pTreatment - pCompare) / Math.sqrt((pooledPrevalence / 2));
I'll work on these, but note:  the proper form (according to the formula):
![image](https://user-images.githubusercontent.com/6818777/113743205-67477680-96d1-11eb-9ced-0099bf0f45af.png)

The formula is pTreatment - pControl. I notice that in feature extraction they do m2 - m1, i'm not sure which is the treatment/control in that formula (variable names FTW).  ALso, it's a bit confusing in this bit of code from FE:
```
    m$sd1 <- sqrt(m$mean1 * (1 - m$mean1))
    m$sd2 <- sqrt(m$mean2 * (1 - m$mean2))
    m$sd <- sqrt((m$sd1^2 + m$sd2^2) / 2)
    m$stdDiff <- (m$mean2 - m$mean1)/m$sd
```

Note that they are sqrt() for sd1 and sd2, but then squaring those (to revert the square root) before averaging the two values (by adding them together, then divide by 2).  IT's a bit of a round-about way of getting to the right answer.

To your note:

> I think the idea with pooledPrevalence is to compute the overall SD? That should take the form:
> SD_overall = SQRT((SD_t ^2 + SD_c^2) / 2)

That would be true if SD_t was actually the sqrt(pTreatment * (1.0 - pTreatment)) and SD_c was sqrt((pCompare * (1.0 - pCompare)).

So, I did invent a new term 'pooledPrevalence' because what I was calculating wasn't exactly a standard deviation, but I needed a value to check for 0. However, I can do the entire denominator calcuation (which I can call sdOverall) up front, and if it is zero, handle the zero case.  I'll put that change in.

We still need a ruling on if it should be pTreatment - pCompare or the other way, but from the Java code structure perspective, the StdDiff is determine by a PrevlanceItem.calcDiff(PrevalenceItem other), and we're assuming the 'other' in this call is the 'thing to compare'.

2021-04-06 16:36 UTC, chrisknoll commented
@anthonysena I made updates, let's get feedback from @schuemie and @pbr6cornell on if it should be T-C or C-T.  Also, I'm considering updating the variable pTreatment to pTarget.

The core of the question is: if the prevalence is greater in T, should the value be positive or negative?  If it should be positive, then it should be pT - pC. If it should be negative, it should be pC - pT.

2021-04-06 18:02 UTC, chrisknoll commented
Ok, based on comments, I've called the 'pooledPrevlance' 'pooledError' since that reflects what that value is.  I'm leaving it as pT - pC for now, and we'll revisit if we decide that we do want it pC - pT, but I feel that feature extraction will want to change to mean1 - mean2.

I think I covered all the comments so far.

2021-04-07 12:54 UTC, anthonysena commented
Thanks @chrisknoll for digging into this. A few comments:

> @anthonysena I made updates, let's get feedback from @schuemie and @pbr6cornell on if it should be T-C or C-T. Also, I'm considering updating the variable pTreatment to pTarget.

T-C is the way to go. I opened up https://github.com/OHDSI/FeatureExtraction/issues/123 to address this on the FE side.

2021-04-07 12:55 UTC, anthonysena approved these changes

2021-04-07 19:30 UTC, merged