Checking of age value was added
OHDSI/WebAPI pull request #1822
Opened 2021-03-19 12:38 UTC by ssuvorov-fls

fixes https://github.com/OHDSI/Atlas/issues/2495

2021-03-19 14:00 UTC, chrisknoll commented
Hi, I'm not sure if this PR is simply a matter of 'adding a check age validator'?  If I look at the issue, and look at what this PR says it's doing, I would have expected to see a new checker added, and a call made to it to validate check age.  But, there's more happening here.

Could you go into some detail about the new classes you added, why you refactored, why you need a 'max recursion', and what 'fakeTrueValidator' means?

2021-03-19 14:10 UTC, ssuvorov-fls commented
I need more than one checker because i need to check a value inside array and nested arrays. 
Max recursion value is used to determine who many times array of CriteriaGroup can be nested inside another CriteriaGroup.
FakeTrueValidator is the last validator in chain of nested validators for CriteriaGroup (i can't use null there).
Age is checked in DemographicHelper.prepareAgeBuilder() function.
Refactoring was made to support iterable validator for arrays and group valudators inside both iterable validators

2021-03-19 14:21 UTC, chrisknoll commented
Ok, Let's rename 'FakeTrue' to 'DefaultTrue'.
For the DemographicHelper, looks like that validates the age criteria in a DemographicCriteria, but you can specify age in other criteria, so question is if that criteria is also being checked in ConditionOccurrence, DrugExposure, etc. (not sure if this logic uss the validation rules from Circe or if this is just specific to IR Analysis).
For Max_recursion:  why do we need to limit this?   Any technical limit to recursion will be reached when trying to create the nested criteria so I'm not sure we need to add the complication of a notion of 'max recursion'..

2021-03-19 14:31 UTC, ssuvorov-fls commented
Max recursion must be used because the chain of validators is created statically before it is used and I get stack overflow without this parameter.
I'll check age parameter in other classes and rename classes with "Fake" in their names

2021-03-21 08:08 UTC, ssuvorov-fls commented
I've deleted recursion in builders and moved it to validators, so nested validators will be created during checking
Also I've created validators for date range, numeric range and period values inside criteria

2021-03-22 19:11 UTC, chrisknoll commented
Question:  I noticed a few criteria checks being applied to constructs defined in Circe (such as CriteriaGroups, ConditionEra, etc), vs. other checks that are being applied to constructs that are part of WebAPI (ie: the analysis design objects like CohortCharacterizaton or others).  Should those checks being applied to Circe be part of the Circe package, and WebAPI just calls out to Circe to check the values, or is the mechanism from Circe a different thing than what's being applied here?

2021-03-23 11:07 UTC, ssuvorov-fls commented
The idea was to create new mechanism that will allow checking of all entities not only cohorts. So the checking of CriteriaGroups, different criterias, cohorts and so on will gradually move to new checking mechanism from circe

2021-03-24 16:27 UTC, chrisknoll commented
> So the checking of CriteriaGroups, different criterias, cohorts and so on will gradually move to new checking mechanism from circe

If you're saying that we'll move the checking code out of circe and into web api (move to new checking mechansim from circe), then I need to object to this:  we have been trying to modularize the code around WebAPI by pulling out functionality from a monolithic codebase.  We did this with Circe and we have done this with Charactierization (and externalized standard interfaces to StandardAnalysisAPI, etc).  So, to pack validation logic from these external sources into WebAPI would be moving in the wrong direction.

2021-03-24 16:41 UTC, ssuvorov-fls commented
No, not into webapi, but into new checking mechanism. It can be moved to another module, may be circe or new one.

2021-03-24 18:16 UTC, chrisknoll commented
Thanks for the clarification. I think a base capability around 'checker definitions' allowing context-specific validation would be an awesome capability to develop, and then each of our individual components can implement 'standardized' validation rules based on that general capability.  Certainly that can start in WebAPI, but then we can refactor it out to something generalized and have our individual repositories depend on that for their own validation.

2021-03-24 18:39 UTC, ssuvorov-fls commented
You are absolutely right. That is the main idea of new checking mechanism

2021-03-30 11:59 UTC, anton-abushkevich requested changes

2021-03-30 11:59 UTC, anton-abushkevich commented on src/main/java/org/ohdsi/webapi/check/validator/common/ArrayForEachValidator.java
> +    final private List<Validator<T>> validators;
make it ``private final`` please, in that order. 
other field (``validatorGroups``) can also be final

2021-03-30 11:59 UTC, anton-abushkevich commented on src/main/java/org/ohdsi/webapi/check/validator/ValidatorGroup.java
> +    private Function<T, Boolean> conditionGetter = t -> true;
``= t -> true`` - is it necessary? you rewrite it in constructor and it is already ``t -> true`` in ``ValidatorGroupBuilder``.
also make fields ``private final``.

2021-03-30 12:04 UTC, ssuvorov-fls commented on src/main/java/org/ohdsi/webapi/check/validator/common/ArrayForEachValidator.java
> +    final private List<Validator<T>> validators;
fixed

2021-03-30 13:37 UTC, anton-abushkevich commented on src/main/java/org/ohdsi/webapi/check/validator/ValidatorGroup.java
> +    private Function<T, Boolean> conditionGetter = t -> true;
also make fields ``private final`` please

2021-03-30 13:42 UTC, ssuvorov-fls commented on src/main/java/org/ohdsi/webapi/check/validator/ValidatorGroup.java
> +    private Function<T, Boolean> conditionGetter = t -> true;
sorry, fixed

2021-03-30 13:44 UTC, anton-abushkevich approved these changes

2021-03-30 13:44 UTC, merged