Azure Synapse Analytics Dedicated dialect support
OHDSI/WebAPI pull request #2074
Opened 2022-08-15 16:40 UTC by alex-odysseus

Addresses https://github.com/OHDSI/WebAPI/issues/2071

To be aligned with https://github.com/OHDSI/WebAPI/pull/2073

It can be merged only after releasing of the corresponding libraries:
- DatabaseConnector (@schuemie please support to merge https://github.com/odysseusinc/DatabaseConnector/tree/synapse into https://github.com/OHDSI/DatabaseConnector/tree/develop and release after)
- SqlRender (@schuemie please support to merge https://github.com/odysseusinc/SqlRender/tree/synapse into https://github.com/OHDSI/SqlRender/tree/develop and release after)
- CommonDataModel (@clairblacketer please support to merge https://github.com/odysseusinc/CommonDataModel/tree/synapse into https://github.com/OHDSI/CommonDataModel/tree/main)
- ARACHNE Commons (https://github.com/OHDSI/ArachneCommons/tree/synapse to be merged to https://github.com/OHDSI/ArachneCommons/tree/1.17.x and released after)

2022-09-20 12:54 UTC, anthonysena requested changes

2022-09-20 12:54 UTC, anthonysena commented on pom.xml
> +    <SqlRender.version>1.9.444-SNAPSHOT</SqlRender.version>
Please use the recently released v1.10.0 of SqlRender.

2022-09-28 20:54 UTC, alex-odysseus commented on pom.xml
> +    <arachne.version>1.17.444-SNAPSHOT</arachne.version>
1.17.3

2022-09-29 01:33 UTC, chrisknoll commented
Also, please merge with master and resolve conflicts.

2022-10-03 19:03 UTC, closed without merging

2022-10-03 19:03 UTC, alex-odysseus commented
Closing as been replaced by https://github.com/OHDSI/WebAPI/pull/2097