Upgraded libraries to versions listed as Spring Boot 2.7 dependencies
OHDSI/WebAPI pull request #2202
Opened 2023-02-08 04:23 UTC by ecruz165

Removed the following unused libraries:
- org.ehcache:ehcache 3.8.1
- javax.cache:cache-api 1.0.0
- commons-httpclient:commons-httpclient 3.1

Upgraded the following to versions provided by SPring Boot 2.7 
-- org.apache.commons:commons-lang3 3.9 -> 3.12.0
-- com.google.code.gson:gson 2.8.9 -> 2.9.0
-- com.zaxxer:HikariCP 3.3.1 -> 4.0.3
-- com.microsoft.sqlserver:mssql-jdbc 9.2.1.jre8 -> 10.2.1.jre8

2023-02-08 12:39 UTC, chrisknoll commented
Our Spring Boot version seems to be 1.5 (at least according to this line in the pon):
```
<spring.boot.version>1.5.22.RELEASE</spring.boot.version>
```

Will these updates cause a conflict with the current version of spring boot?

2023-02-11 17:39 UTC, ecruz165 commented
@chrisknoll I am aware we are on spring boot 1.5. Maybe the title of PR caused unnecessary concern.

As you might know, spring bundles third-party version numbers of libraries usually paired with spring boot applications to provide features. So I identified the libraries listed in WebAPI that can safely be bumped so that when we arrive at the goal of being on Spring Boot 2.7.x and then we can remove the explicit versioning and let the listed versions listed in Spring Boot handle the upgrading of libraries instead of bumping libs individually.
https://docs.spring.io/spring-boot/docs/2.7.0/reference/html/dependency-versions.html#appendix.dependency-versions

So yes, it is safe to update these libraries> I ran the unit test and the supplied integration tests and all ran to success.

2023-02-11 21:59 UTC, chrisknoll commented
Excellent! Thank you, pushing forward the dependencies to current versions is an important task.

2023-02-11 22:01 UTC, chrisknoll requested changes
(deleted)

2023-02-11 22:01 UTC, chrisknoll requested changes

2023-02-11 22:01 UTC, chrisknoll commented on pom.xml
> +<!--    </dependency>-->
Can we remove these lines?

2023-02-14 17:52 UTC, ecruz165 commented on pom.xml
> +<!--    </dependency>-->
removed.  I did notice a manual approach to caching was implemented. Any reason why we chose manually cache implementation over Ehcache? I am very experienced in implementing Ehcache in case there is a future need.

2023-04-04 13:05 UTC, anthonysena commented
These changes are related to upgrading WebAPI to Spring Boot 2.x

2023-04-04 13:05 UTC, anthonysena approved these changes

2023-04-04 13:07 UTC, merged