Filter cohorts and concepts by permission
OHDSI/WebAPI pull request #2245
Opened 2023-04-04 13:31 UTC by rkboyce

2023-04-20 17:59 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/security/PermissionController.java
>      ) throws Exception {
Also, there's some overloading of terms 'role' where in this context, it is 'READ', 'WRITE' for 'role' but in other places we have 'Admin' as a role and 'Atlas User' as a role...but the latter roles maps to a shiro 'group' (which you assign permissions to'....we could probably interchange groups and roles, however, the AccessType is neither a group or a role...so...I don't have a solution here, just pointing out the differences in context.

It's almost like we're talking about a 'permission type'  .. permission to read, permission to write.

2023-04-20 17:59 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/service/ConceptSetService.java
> +    @Value("#{'${security.conceptsetsauthview}'.equals('True')}")
we should look at places where we have 'enable' flags set, I'm not sure we look for the string 'True', but I could be wrong. let's find other examples and try to follow precedent.

2023-04-20 17:59 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/service/ConceptSetService.java
> +   	       if (conceptsetsauthview == false) { // don't filter based on read permissions
Is this something we want on a case-by-case basis (ie: conceptsetauthview can be false but cohortdefinitionauthview can be set to true)?  Part of me thinks all-or-nothing makese sense and is easier to configure (ie: works the same everywhere) vs you do want to restrict one set of assets to only return those with perms vs. another asset you would let anyone see everything.

2023-05-18 13:14 UTC, chrisknoll commented
@rkboyce ,  I noticed when we did the walkthrough and we enabled the filter on the server, the asset list returned nothing until I created a new asset and it got the read perm assigned to it. I wanted to ask: have we thought about considering 'read access' if you have write? This way, if we enable it, anything I've been granted write access will appear, plus anything that someone grants me read access to.   Basically the filter becomes `if (canRead || canWrite|  then show item`.  Is that possible or was there a reason why we had to explicitly look for the granted permission?  The only reason why I bring this is that it seems if you can write to something then you can also read it...

2023-07-19 11:24 UTC, rkboyce commented on src/main/java/org/ohdsi/webapi/service/ConceptSetService.java
> +    @Value("#{'${security.conceptsetsauthview}'.equals('True')}")
This was changed to check for boolean false on a parameter that is more akin to others in the settings.xml

```  @Value("#{'${security.defaultglobalreadpermissions}'.equals(false)}")```

2023-07-19 11:26 UTC, rkboyce commented on src/main/java/org/ohdsi/webapi/service/ConceptSetService.java
> +   	       if (conceptsetsauthview == false) { // don't filter based on read permissions
The more general parameterized value is now defaultglobalreadpermissions - so, all or nothing

2023-07-19 11:28 UTC, rkboyce commented on src/main/java/org/ohdsi/webapi/service/ConceptSetService.java
> +					                .collect(Collectors.toList()));
Sorry about not implementing this way. It is a more elegant way to do things. It's my inexperience with reviewing comments on draft pull requests that caused me to miss this suggestion. I had carried through the less elegant coding approach throughout all of the other cases (IR, estimation, prediction, etc.) before seeing this.

2023-07-23 02:20 UTC, rkboyce commented on src/main/java/org/ohdsi/webapi/security/PermissionController.java
>      ) throws Exception {
I addressed this the overloading of the 'role' string by using 'permType' as the parameter. The function name is now listAccessesForEntityByPermType  used for the /access/{entityType}/{entityId}/{permType} endpoint with WRITE as the default permission type sent from the client. This distinguishes it from listAccessesForEntity  which is used for the /access/suggest endpoint.  I did not get a chance to test if the AccessType enum would work instead of string "READ" and "WRITE".

2023-07-23 02:26 UTC, rkboyce commented
In response to the last comment about "have we thought about considering 'read access' if you have write" -- yes, it is implemented that way and seems to function correctly based on my tests. 

This updated draft pull request implements the READ permissions filtering across all the following applications in Atlas:
- concept sets
- Cohort definition
- Cohort characterization
- Incident Rates
- Estimation
- Prediction

All have functioned as expected : things are not accessible to a user unless 1) they create the entity (which sets READ and WRITE), or 2) they are given READ permission to the entity

*NOTE:* These changes will need to come with a new system role that the admins could select which I am calling the 'Read Restricted Atlas User' role. I think the following query could be the basis for adding SQL to flyway to create this role: 

```
select distinct sp.*
from ohdsi.sec_role_permission srp 
  inner join ohdsi.sec_permission sp on srp.permission_id = sp.id 
where srp.role_id in (6,10) -- 'cohort reader', 'Atlas Users'
 and sp.value not in 
    (  
    	'conceptset:*:get',
    	'conceptset:*:expression:get',
    	'conceptset:*:version:*:expression:get',    	       
    	--
        'cohortdefinition:*:get',
        'cohortdefinition:*:info:get',
        'cohortdefinition:*:version:get',
        'cohortdefinition:*:version:*:get',        
        --        
	        'cohort-characterization:*:get',
                'cohort-characterization:*:generation:get',
		'cohort-characterization:generation:*:get',
		'cohort-characterization:design:get',
		'cohort-characterization:*:design:get',
		'cohort-characterization:design:*:get',
		'cohort-characterization:*:version:get',
		'cohort-characterization:*:version:*:get',
		--
		'pathway-analysis:*:get',
		'pathway-analysis:*:generation:get',
		'pathway-analysis:generation:*:get',
		'pathway-analysis:generation:*:result:get',
		'pathway-analysis:generation:*:design:get',
		'pathway-analysis:*:version:get',
		'pathway-analysis:*:version:*:get'
		--
		'ir:*:get',
		'ir:*:copy:get',
		'ir:*:info:get',
		'ir:*:design:get',
		'ir:*:version:get',
		'ir:*:version:*:get'
		--		
		'estimation:*:get',
		'estimation:*:copy:get',
		'estimation:*:download:get',
		'estimation:*:export:get',
		'estimation:*:generation:get'
               'comparativecohortanalysis:*:get',
		--
		'prediction:*:get',
		'prediction:*:copy:get',
		'prediction:*:download:get',
		'prediction:*:export:get',
		'prediction:*:generation:get',
		'prediction:*:exists:get',
                'plp:*:get'
    )
order by sp.value 
;
```

2023-07-24 18:18 UTC, chrisknoll requested changes

2023-07-24 18:18 UTC, chrisknoll commented on pom.xml
> +    <security.defaultGlobalReadPermissions>false</security.defaultGlobalReadPermissions>
We should default this to true, and rely on settings.xml to override this setting. This will maintain current behavior between versions.

2023-07-24 18:18 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/cohortcharacterization/CcController.java
> +    @Value("#{'${security.defaultglobalreadpermissions}'.equals(false)}")
I believe I will want this to be camelCase based on other params: defaultGlobalReadPermissions,   Also we should check if we can interpret this as a boolean value directly instead of a string compare.

2023-07-24 18:18 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/estimation/EstimationController.java
> +  private boolean defaultglobalreadpermissions;
Style: defaultGlobalReadPermissions

2023-07-24 18:18 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/estimation/EstimationController.java
> +    }
I believe this was mentioned before but you can put the filter conditional in the stream expression:

```
      return StreamSupport.stream(service.getAnalysisList().spliterator(), false)
	.filter(!defaultglobalreadpermissions  ? candidateEstimation -> permissionService.hasReadAccess(candidateEstimation) : candidateEstimation -> true)
	.map(analysis -> {
	    EstimationShortDTO dto = conversionService.convert(analysis, EstimationShortDTO.class);
	    permissionService.fillWriteAccess(analysis, dto);
	    permissionService.fillReadAccess(analysis, dto);
	    return dto;
	  })
	.collect(Collectors.toList());
```

2023-07-24 18:18 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/pathway/PathwayController.java
> +		}
I believe this can be written same as in Estimation:

```
	return pathwayService.getPage(pageable)
		.filter(!defaultglobalreadpermissions  ? pa -> permissionService.hasReadAccess(pa) : pa -> true)
		.map(pa -> {
			PathwayAnalysisDTO dto = conversionService.convert(pa, PathwayAnalysisDTO.class);
			permissionService.fillWriteAccess(pa, dto);
			permissionService.fillReadAccess(pa, dto);
			return dto;
		});

```

2023-07-24 18:18 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/prediction/PredictionController.java
> +	}
Same comment as above: use conditional filter to reduce redundancy.

2023-07-24 18:18 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/prediction/PredictionController.java
> +	 */
Fix indent of comments, should be aligned to the following function.

2023-07-24 18:18 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/service/CohortDefinitionService.java
> +		}
use conditional filter here.

2023-07-24 18:18 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/service/ConceptSetService.java
> +					                .collect(Collectors.toList()));
use conditional filter here.

2023-07-24 18:18 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/service/IRAnalysisService.java
> +	});
use conditional filter here, will simplify code so that you only have the one `getTransactionTemplarte()` call, but within the stream you filter conditionally before mapping.

2023-07-24 18:18 UTC, chrisknoll commented on src/main/resources/application.properties
> +security.defaultglobalreadpermissions=${security.defaultGlobalReadPermissions}
Follow camelCase style, for example `security.cas.callbackUrl`.  So, set this to `security.defaultGlobalReadPermissions`

2023-07-25 23:35 UTC, rkboyce commented on src/main/java/org/ohdsi/webapi/cohortcharacterization/CcController.java
> +    @Value("#{'${security.defaultglobalreadpermissions}'.equals(false)}")
I completed this change. ty

2023-07-25 23:35 UTC, rkboyce commented on pom.xml
> +    <security.defaultGlobalReadPermissions>false</security.defaultGlobalReadPermissions>
corrected now and tested that setting the variable false in the WebAPIConfig/settings.xml works

2023-07-25 23:36 UTC, rkboyce commented on src/main/resources/application.properties
> +security.defaultglobalreadpermissions=${security.defaultGlobalReadPermissions}
corrected

2023-07-25 23:36 UTC, rkboyce commented on src/main/java/org/ohdsi/webapi/estimation/EstimationController.java
> +  private boolean defaultglobalreadpermissions;
corrected

2023-07-25 23:37 UTC, rkboyce commented on src/main/java/org/ohdsi/webapi/cohortcharacterization/CcController.java
> +			if (defaultglobalreadpermissions == true) { // don't filter based on read permissions
corrected

2023-07-25 23:41 UTC, rkboyce commented
A detail worth mentioning  - were were curious what would happen if a person without read access knew the URL to an entity and tried a GET. I tested as follows:

1) logged in as an admin, created a brand new entity (did it for a few types e.g., cohort definition, estimation, etc)

2) copied the URL

3) logged out from the admin account and logged in to a user account without access to the entity

4) put the URL in the browser

The result is an empty page with no message at all. The server simply returns a 403 with an empty body in the response. Atlas renders nothing. So, I think it is Ok for now.

2023-07-25 23:47 UTC, chrisknoll commented
Yes, that's fine. Ok, if you're done with your part, I will merge this into a new feature branch under WebAPI so I can put in the final changes. Let me know if you are ready for me to do that.

2023-07-28 18:42 UTC, merged

2023-07-28 21:51 UTC, rkboyce commented
All good here!