Fix issue #2256
OHDSI/WebAPI pull request #2269
Opened 2023-05-09 11:20 UTC by TomWhite-MedStar

Fix issue #2256.  Confirmed now works on Databricks.
Root cause may be issue in SqlRender for Spark.

2023-05-09 16:04 UTC, anthonysena commented on src/main/resources/ddl/achilles/achilles_result_concept_count.sql
> +/* Fix bug in SqlRender for Spark.  When list variables for insert as below, incorrect SQL is generated
@TomWhite-MedStar - just a note here: we'd prefer not to remove the columns from the `INSERT` portion of the query. That said, we'll need to dig into why this translation is not working in Spark as it may be a bug in SqlRender.

2023-05-11 14:35 UTC, chrisknoll commented on src/main/resources/ddl/achilles/achilles_result_concept_count.sql
> +/* Fix bug in SqlRender for Spark.  When list variables for insert as below, incorrect SQL is generated
Agree with Sena, we should be explicit about col names because the order of values form the select may not be the inferred order of the insert.

2023-05-16 13:34 UTC, TomWhite-MedStar commented on src/main/resources/ddl/achilles/achilles_result_concept_count.sql
> +/* Fix bug in SqlRender for Spark.  When list variables for insert as below, incorrect SQL is generated
@chrisknoll and @anthonysena , I tested the as-is code on SqlRender 1.15.0 and it still has the problem shown in issue #2256.

2023-05-16 17:50 UTC, chrisknoll commented on src/main/resources/ddl/achilles/achilles_result_concept_count.sql
> +/* Fix bug in SqlRender for Spark.  When list variables for insert as below, incorrect SQL is generated
Ok, let me figure out who can focus on this issue on the SqlRender side, and see if we can get a 1.15.1 release so that your PR can reference it and we can have this all working.....I hate that it will delay this, but I think that's the proper way to approach it.

2023-05-16 18:04 UTC, chrisknoll commented on src/main/resources/ddl/achilles/achilles_result_concept_count.sql
> +/* Fix bug in SqlRender for Spark.  When list variables for insert as below, incorrect SQL is generated
@TomWhite-MedStar , I'm not able to find the issue in OHDSI/SqlRender so I think if we're going to get traction on this, we need a simple test case that demonstrates the multiple CTEs in the insert that get split into the double `WITH` clause (instead of with cteA as ( ) ... , cteB as ()...)

I'm sorry to bother you but could you provide a simple SQL statement with the two CTE expressions that gets translated over to 2 WITH statements?  We can feed this over into the SqlRender repo with steps to reproduce and can probably get addressed faster.  If you give me the problematic OHDSI-SQL statement that has problems translation, I will write the sample R script that will make a call to SqlRender to show the problem.

2023-05-16 18:07 UTC, chrisknoll commented on src/main/resources/ddl/achilles/achilles_result_concept_count.sql
> +/* Fix bug in SqlRender for Spark.  When list variables for insert as below, incorrect SQL is generated
@TomWhite-MedStar I'm going to grab your achilles DDL link you put in your issue as the test case, and possibly simplify it to make it easier to diagnose on the SqlRender side.   If I can replicate it in R then I can submit it as an issue over to SqlRender.

2023-05-17 00:55 UTC, TomWhite-MedStar commented on src/main/resources/ddl/achilles/achilles_result_concept_count.sql
> +/* Fix bug in SqlRender for Spark.  When list variables for insert as below, incorrect SQL is generated
@chrisknoll , excellent point.  I  refactored the query so that it runs fine in SqlRender for Spark.

2023-05-17 12:34 UTC, chrisknoll requested changes

2023-05-17 12:34 UTC, chrisknoll commented on src/main/resources/ddl/achilles/achilles_result_concept_count.sql
> +DROP TABLE IF EXISTS #tmp_concepts;
The IF EXISTS may not be valid syntax on all our supported platforms....and I'm not sure it's necessary since we just created it earlier.   And, if you have a typo in the table name, then it's not going to drop it because the typo-d table name won't actually exist and it won't drop the actual table you want. So, I suggest removing `IF EXISTS`.

2023-05-17 12:49 UTC, TomWhite-MedStar commented on src/main/resources/ddl/achilles/achilles_result_concept_count.sql
> +DROP TABLE IF EXISTS #tmp_concepts;
@chrisknoll , I found when  I ran this repeatedly, if failed is the tables already existed.
I fixed the syntax so that it matches what Sql Server expects and confirmed that it looks correct for all databases in SQLRender Developer.

2023-05-17 12:52 UTC, chrisknoll commented on src/main/resources/ddl/achilles/achilles_result_concept_count.sql
> +DROP TABLE IF EXISTS #tmp_concepts;
Ok, sounds good, it's odd that you would see tables exist when these should only be visible in the session (connection) that created them, or in cases where we use 'fake' temp tables via temp schemas, we prefix temp tables with a unique session id (meaning maybe the unique session ID isn't unique across connections, which would be odd).

In any case, the modification is more compatible, so thank you for that change.

2023-05-17 12:53 UTC, chrisknoll approved these changes

2023-05-17 12:53 UTC, merged