Finalizing externalizing vocabulary search apache solr implementation
OHDSI/WebAPI pull request #2308
Opened 2023-09-11 12:04 UTC by alex-odysseus

2023-09-13 18:01 UTC, chrisknoll commented
The test failure is pre-existing, and is related to a change in the underlying sql, I can post a commit to this branch to fix.

2023-10-04 18:11 UTC, anthonysena commented on src/main/java/org/ohdsi/webapi/cohortanalysis/HeraclesConfigurationInfo.java
> +import org.ohdsi.info.ConfigurationInfo;
Noting that this class was moved to the StandardizedAnalysisAPI project hence the namespace change.

2023-10-04 18:11 UTC, anthonysena commented on src/main/java/org/ohdsi/webapi/conceptset/ConceptSetExport.java
> +import org.ohdsi.vocabulary.Concept;
Noting that this class was moved to the StandardizedAnalysisAPI (v1.5.0) project hence the namespace change.

2023-10-04 18:13 UTC, anthonysena requested changes

2023-10-04 18:13 UTC, anthonysena commented on src/test/resources/cohortresults/sql/cohortSpecific/getTimeToEventDrilldown-expected.sql
> +                CAST(CASE WHEN analysis_id = 1805 THEN stratum_2 ELSE null END AS INT) as stratum_1, sum(count_value) as count_value
@alex-odysseus - the changes for `src/test/resources/cohortresults/sql/cohortSpecific/getTimeToEventDrilldown-expected.sql` appear unrelated to the Solr implementation. Can this be removed?

2023-10-04 18:17 UTC, anthonysena commented on src/test/resources/cohortresults/sql/cohortSpecific/getTimeToEventDrilldown-expected.sql
> +                CAST(CASE WHEN analysis_id = 1805 THEN stratum_2 ELSE null END AS INT) as stratum_1, sum(count_value) as count_value
From offline discussion this resolved a problem with unit test failures. Thanks @alex-odysseus!

2023-10-04 18:17 UTC, anthonysena approved these changes

2023-10-04 18:23 UTC, merged