Application usage statistics
OHDSI/WebAPI pull request #2387
Opened 2024-08-27 18:31 UTC by alex-odysseus

#2329

2024-08-27 18:47 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/statistic/controller/StatisticController.java
> +@ConditionalOnProperty(value = "audit.trail.enabled", havingValue = "true")
If Audit Trail feature is not enabled the Controller is not efficient

2024-08-27 18:47 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/statistic/controller/StatisticController.java
> +        CSV, JSON
Both CSV and JSON output formats should be supported

2024-08-27 18:50 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/statistic/controller/StatisticController.java
> +            throw new RuntimeException(ex);
We may add some logging here

2024-08-27 18:54 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/statistic/controller/StatisticController.java
> +    private void updateExecutionStatisticsHeader(boolean showUserInformation) {
Both methods to be replaced by extra two static constants!

2024-08-27 18:55 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/statistic/dto/SourceExecutionDto.java
> +    private String userID;
userId

2024-08-27 19:11 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/statistic/service/StatisticService.java
> +    // TODO remove value
To be configured via properties

2024-08-27 19:20 UTC, alex-odysseus commented on src/main/resources/db/migration/postgresql/V2.14.0.20231206190600__fixing_statistics_enpoint_permission_method.sql
> +UPDATE ${ohdsiSchema}.sec_permission SET value='statistic:executions:post'
We may combine both scripts into one

2024-12-27 17:48 UTC, anthonysena requested changes

2024-12-27 17:48 UTC, anthonysena commented on src/main/java/org/ohdsi/webapi/statistic/controller/StatisticController.java
> +@ConditionalOnProperty(value = "audit.trail.enabled", havingValue = "true")
Is the intent here to make the `/statistic/` end-point available based on the `audit.trail.enabled` property? Seems a little confusing to make an endpoint conditional vs. having it always available and to have it return based on the status of the configuration of the application.

2024-12-27 17:48 UTC, anthonysena commented on src/main/java/org/ohdsi/webapi/statistic/controller/StatisticController.java
> +            throw new RuntimeException(ex);
When will this be added?

2024-12-27 17:48 UTC, anthonysena commented on src/main/java/org/ohdsi/webapi/statistic/controller/StatisticController.java
> +    private void updateExecutionStatisticsHeader(boolean showUserInformation) {
When will this be replaced?

2024-12-27 17:48 UTC, anthonysena commented on src/main/java/org/ohdsi/webapi/statistic/dto/SourceExecutionDto.java
> +    private String userID;
When do you plan to change this?

2024-12-27 17:48 UTC, anthonysena commented on src/main/java/org/ohdsi/webapi/statistic/service/StatisticService.java
> +    // TODO remove value
So will you remove this then?

2024-12-27 17:48 UTC, anthonysena commented on src/main/resources/db/migration/postgresql/V2.14.0.20231206190600__fixing_statistics_enpoint_permission_method.sql
> +UPDATE ${ohdsiSchema}.sec_permission SET value='statistic:executions:post'
Yes, please do and make sure the prefix of the file is v2.15...

2025-01-08 13:00 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/statistic/controller/StatisticController.java
> +@ConditionalOnProperty(value = "audit.trail.enabled", havingValue = "true")
I personally see no problem that some of the endpoints are not available if an appropriate configuration is not at place

2025-02-25 17:25 UTC, chrisknoll commented
Docker build fails due to (presumably) a JDK 11 docker config.   We discussed and possible least-friction solution is to check the stream syntax on regex Matcher in the stream API.   Failing that, may need to find an ARM compatible JDK 8 for docker.

2025-03-04 14:48 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/statistic/controller/StatisticController.java
> +@ConditionalOnProperty(value = "audit.trail.enabled", havingValue = "true")
I agree with @anthonysena, it is confusing because people will look at api docs and think they can call an endpoint, but it won't exist, which is confusing.

I don't see any documentation that describes that this end-piont doesn't exist when the configuration is not set.

We have rules about opt-in flags for default behavior (such as logging should be turned on/off, or auditing is enabled/distables) but the invocation of a end-point is the opt-in request of the user.   If it's not enabled, it would be better to raise an error message saying 'auditing is not enabled' then return a 404 that a conditional-endpoint does not exist.

2025-03-11 10:30 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/statistic/controller/StatisticController.java
> +@ConditionalOnProperty(value = "audit.trail.enabled", havingValue = "true")
Changed as suggested

2025-03-11 13:25 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/statistic/controller/StatisticController.java
> +    		throw new NotFoundException("Audit Trail functionality should be enabled (audit.trail.enabled) to serve this endpoint");
NotFound results in a 404, correct? We said that it would be confusing if someone looked at an api and attempted to call an endpoint and it was not found.  I think we mentioned raising an error, such that it could return an HTTP 500 or some other HTTP code that represents an error other than 'not found'?

2025-03-11 16:50 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/statistic/controller/StatisticController.java
> +    		throw new NotFoundException("Audit Trail functionality should be enabled (audit.trail.enabled) to serve this endpoint");
I misread your passage, corrected to the internal server error

2025-03-18 12:34 UTC, chrisknoll approved these changes

2025-03-18 12:35 UTC, merged

2025-04-10 17:14 UTC, pieterlukasse commented
hi @alex-odysseus , @chrisknoll sorry for the late review comment here, but I just wanted to raise a flag here. If I understand these changes correctly, the `audit.trail.enabled` setting already existed before. The behavior of this config setting was that it would ensure things got logged to some local `audit.log` file. I can imagine many installations might have turned this ON. Now, with this PR, the behavior changes significantly, by opening up new endpoints. This will happen silently, and therefore I think it is a potential security issue. Instead, I think this new feature should be controlled by a _new_ config option that is set to `false` by default. Can you please consider changing this?

2025-04-10 19:18 UTC, alex-odysseus commented
Pieter, newly added endpoints should be available for the administrators only by default @pieterlukasse

2025-04-14 12:46 UTC, pieterlukasse commented
@alex-odysseus thanks for the clarification. 
Still, I think the change might come as a surprise to some.
As an admin, I would not like endpoints (albeit admin ones) to be silently opened. 
Then again, I believe all work you are doing is still on a dev branch and nothing is officially release yet, correct?

2025-04-14 19:00 UTC, chrisknoll commented
Thanks @pieterlukasse , it's an interesting perspective.   From a WebAPI perspective, we introduce new endpoints quite a bit.  Never as a result of a hotfix release (ie x.x.1 -> x.x.2) but minor releases which add new non-backwards-breaking features to the app will bring along new endpoints (usually a new feature is exposed as a new endpoint).  The hint to the admins is that if they are installing a new version of WebAPI (minor or major version increment) they should expect new endpionts.

Now, have we been proactive about announcing which new endpoints exist?  Other than the automatic REST documentation that is generated that gives all the service endpoints, I don't think we make a habbit of itemizing each new endpint in our release notes, we usually just declare the new feature, point it to the PR, and then if you want to know the technical details, it's there.

Could we do more than that? Possibly, given the resources.   Should anyone be surprised about new endpoints in new releases?  Probably not, that should almost be the expectation.

In this specific case, a couple endpoints were added to provide reporting on the audits that are enabled via config.  So, the release notes will say something about exposing audit train reports, and pointing to the PR that implements.

2025-04-15 17:51 UTC, pieterlukasse commented
Thanks for clarifying @chrisknoll . It helps me understand better how you are dealing with this. If this is mentioned in the release notes and points to the PR, then this sounds like a reasonable approach to me. It could be useful to add a line to this PR description stating that an existing config setting is being reused/partially repurposed to do something new.