Tools module functionality
OHDSI/WebAPI pull request #2389
Opened 2024-08-30 13:52 UTC by alex-odysseus

Addressing #2330

- CRUD operations implemented
- a separate Permission Schema has been created

2024-08-30 13:55 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/tool/Tool.java
> +    private Boolean isEnabled;
The property name should be renamed to 'enabled'

2024-08-30 13:56 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/tool/ToolController.java
> +import javax.ws.rs.*;
Imports with * should be eliminated

2024-08-30 13:58 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/tool/converter/ToolConvertor.java
> +    private void setCreationDetails(Tool tool, Instant currentInstant) {
I don't think we need two separate methods

2024-08-30 13:59 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/util/DateUtils.java
> +public class DateUtils {
The purpose of this class is unclear SimpleDateFormat usage should be sufficient

2024-08-30 14:00 UTC, alex-odysseus commented on src/main/resources/db/migration/postgresql/V2.13.1.20231213141052__create_table_tools.sql
> +CREATE TABLE IF NOT EXISTS ${ohdsiSchema}.tool (
We can combine all migration scripts into one

2024-08-30 14:02 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/security/model/ToolPermissionSchema.java
> +        put("tool:%s:delete", "Delete Tool with id = %s");
I am afraid that the notation doesn't coincide with what is inserted by the migration scripts

2024-09-10 01:38 UTC, chrisknoll commented on src/main/resources/db/migration/postgresql/V2.13.1.20231213141052__create_table_tools.sql
> +CREATE TABLE IF NOT EXISTS ${ohdsiSchema}.tool (
I'd prefer if you did this

2024-11-04 17:14 UTC, chrisknoll commented on src/main/resources/db/migration/postgresql/V2.13.1.20231213141052__create_table_tools.sql
> +CREATE TABLE IF NOT EXISTS ${ohdsiSchema}.tool (
In addition, please mark these migrations attached to V2.15

2024-11-04 17:16 UTC, chrisknoll commented
Hello Everyone.  Once the migration scripts are combined and the changes @alex-odysseus requests have been implemented, I can pull down the branches to check the functionality.

2024-12-27 17:38 UTC, anthonysena requested changes

2024-12-27 17:38 UTC, anthonysena commented on src/main/java/org/ohdsi/webapi/security/model/ToolPermissionSchema.java
> +        put("tool:%s:delete", "Delete Tool with id = %s");
Checking this without security enabled seemed to work fine but your comment seems correct and this should be corrected before we merge this work.

2025-01-10 13:33 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/security/model/ToolPermissionSchema.java
> +        put("tool:post", "Create a Tool");
This won't work: what will happen is that when the Tool asset is deleted, all these permissions will be deleted and everyone will lose the ability to create and update a tool.

This is an example of the complication of the permission implementation we have in webapi that we'll want to resolve in 3.x or 4.x.  

For details on how the non-entity specific permissions caused issues, you can refer to this pr: https://github.com/OHDSI/WebAPI/pull/2413.

Essentially, the only permissions that go into PermissionSchema are those with entity-id context.  The general ones can't be there because deleting one asset will delete the entire (non-asset specific) set of permissions from everyone.

2025-02-11 17:14 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/security/model/ToolPermissionSchema.java
> +        put("tool:post", "Create a Tool");
@alex-odysseus , please provide update to this issue.

2025-02-25 14:38 UTC, merged