Extending Concept Set Items with Annotations
OHDSI/WebAPI pull request #2403
Opened 2024-10-29 11:50 UTC by alex-odysseus

Addressing #2318

2024-10-29 12:13 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/service/ConceptSetService.java
> +                    throw new RuntimeException(e);
Let's add a log entry

2024-10-29 12:15 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/service/ConceptSetService.java
> +    private ConceptSetAnnotation copyAnnotation(ConceptSetAnnotation sourceConceptSetAnnotation, int sourceConceptSetId, int targetConceptSetId){
Please move it down below the public method where it is used

2024-10-29 12:18 UTC, alex-odysseus commented on src/main/java/org/ohdsi/webapi/service/ConceptSetService.java
> +    public AnnotationDTO updateConceptSetAnnotation(@PathParam("id") final int id, AnnotationDTO annotationDTO) throws IOException {
This method is obsolete at this moment, if in the future it will be necessary to add/update a comment to a specific Concept Set Annotation it might be added

2024-10-29 12:24 UTC, alex-odysseus commented on src/main/resources/db/migration/postgresql/V2.14.0.202407161000__conceptset_annotation.sql
> +CREATE SEQUENCE ${ohdsiSchema}.concept_set_annotation_sequence;
Let's combine one migration script

2024-10-29 12:31 UTC, alex-odysseus commented on src/main/resources/i18n/messages_en.json
> +        "metadata": "Metadata"
To be removed

2024-11-04 16:52 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/conceptset/ConceptSet.java
> +@Entity
Please revert this as we have a convention to name the entity, you can see this in CohortDefinition, Source, etc.

2024-11-04 16:52 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/conceptset/ConceptSetGenerationInfo.java
> +@Entity
Same as above, please revert this change.

2024-11-04 16:53 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/conceptset/ConceptSetItem.java
> +@Entity
Same as above, we name Entities.

2024-11-04 16:58 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/security/model/ConceptSetAnnotationPermissionSchema.java
> +    };
This is odd to me: 

Shouldn't the writePermissions contain all permissions related to creating annotations and the read have the ones related to reading annotations?

2024-11-04 17:02 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/service/ConceptSetService.java
> +import org.apache.commons.lang3.StringUtils;
Just might want to check this import (collections4 is something I'm not familiar with).  is there an existing package we depend on that has the function in CollectionUtils that you are using?

Just trying to keep extra dependencies down....when we get to the 3.x line we're going to be combing through the code locating redundant dependcies (ie: libraries that support string manipulation will be de-duplicated)  So if we can remove a source of additional duplication, we should try to do it here.

2024-11-04 17:06 UTC, chrisknoll commented on src/main/resources/db/migration/postgresql/V2.14.0.202407161000__conceptset_annotation.sql
> +CREATE SEQUENCE ${ohdsiSchema}.concept_set_annotation_sequence;
Yes, let's combine into 1 script and also this is targeting v2.15 so if we do create 1 migrations cript let's just make a new one with all the others combined, call it V2.15 ...

2024-11-04 17:07 UTC, chrisknoll commented on src/main/resources/db/migration/postgresql/V2.14.0.202407261000__add_conceptset_version_to_annotation.sql
> +ALTER TABLE ${ohdsiSchema}.concept_set_annotation ADD concept_set_version VARCHAR;
Are we sure VARCHAR is the correct type here?  That will allow 2GB of text

2024-11-04 17:10 UTC, chrisknoll commented
Hi, Everyone. I added comments and if you could address those I will work on pulling the branch down to test.

Specifically, the migration scripts being combined and re-labeled to 2.15 is soemthing I'd like to have changed before pulling it down, because otherwise I'd have to manually roll back the stuff in the 2.14 migrations and then let them re apply from the 2.15 migration, and it gets to be a headache.   Once that's done I can play-test the functionality locally and provide feedback.

2024-11-08 14:32 UTC, chrisknoll commented
Thanks for addressing those requested changes. I'll pull it down and take it for a spin.

2024-12-04 15:16 UTC, chrisknoll requested changes

2024-12-04 15:16 UTC, chrisknoll commented on src/main/java/org/ohdsi/webapi/security/model/ConceptSetPermissionSchema.java
> +        put("conceptset:*:annotation:put", "Create Concept Set Annotation");
These should not be * permissions. What happens is that when you delete the entity, it finds the write permission schema and deletes it, thus deleting the wildcard permission' from all users, and then preventing access to the endpiont for all users.

However, this is what happens when you extend the 'CommonEntity' which you didn't do in this case, however, ou are using a permissionSchema as if it was a common entity, so there may be a little confusion here.

But, in any case, we shouldn't see * permissions in any writePermission schema because these permission schemas are targeting a specific entity ID.

2024-12-06 19:51 UTC, chrisknoll commented
Hi, I am getting an error when I restore to a prior version of the DB and the migration scripts were applied.  

Steps to reproduce:

1. Click Create concept Set (repository concept set)
2. Name it
3. Save it (empty concept set)
4. Observe error:  There was an error saving your concept set'
5. Close editor with X to return to concept set list
6. Observe the new concept set was actually created.
7. Open Concept set
8. Search for a concept
9. Add concept to concept set
10. Try to save again: Observe same error 'There was an error saving your concept set'
11 close and re-open the concept set, and the concept set seems to be saved.

Note: annotation tab is 'disabled' in that clicking it does not swatch tab.
Also, there are no errors in the browser console, and no exceptions seen on the server log, making it hard to diagnose the issue.

2024-12-16 19:40 UTC, chrisknoll commented
I've confirmed that I do not get this error when switching to master/master (atlas/webapi) so there is something related to this branch leading to the described error.

2024-12-17 14:17 UTC, merged