Introduce support for InterSystems IRIS
OHDSI/WebAPI pull request #2416
Opened 2024-12-04 16:03 UTC by bdeboe

This PR introduces support for InterSystems IRIS Data Platform as a new platform, including the SqlRender and Arachne library updates adding IRIS support

Fixes #2409

2024-12-27 16:27 UTC, anthonysena requested changes
This PR looks fine from a functional perspective. I'd like to update this PR to note that this is 'tentative' support for IRIS based on SqlRender's release notes. I'd also like to document how a user obtains the JDBC driver and installs it configure WebAPI to use IRIS.

2024-12-27 16:27 UTC, anthonysena commented on src/main/java/org/ohdsi/webapi/DataAccessConfig.java
> +        supportedDrivers = new String[]{"org.postgresql.Driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver", "oracle.jdbc.driver.OracleDriver", "com.amazon.redshift.jdbc.Driver", "com.cloudera.im
Can you describe how you would download the IRIS JDBC driver? A quick Google search brought me to this page: https://intersystems-community.github.io/iris-driver-distribution/. It would be useful to document this in the pull request and other OHDSI documentation.

2024-12-27 16:27 UTC, anthonysena commented on pom.xml
> +    <SqlRender.version>1.19.1</SqlRender.version>
Noting that SqlRender v1.19.0 [release notes](https://github.com/OHDSI/SqlRender/blob/main/NEWS.md#sqlrender-1190) mentioned that IRIS support is 'tentative'. By extension, we'll view IRIS support as 'tentative' in WebAPI & ATLAS.

2025-01-02 17:02 UTC, bdeboe commented on src/main/java/org/ohdsi/webapi/DataAccessConfig.java
> +        supportedDrivers = new String[]{"org.postgresql.Driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver", "oracle.jdbc.driver.OracleDriver", "com.amazon.redshift.jdbc.Driver", "com.cloudera.im
This is described in our forthcoming DatabaseConnector submission (and taken care of in the `downloadJdbcDrivers()` function, but indeed that isn't obvious from here right now. Is there any place you recommend we can document this? 
Also, since preparing this PR, we've started publishing our JDBC driver on Maven and I'll amend this PR with a `webapi-iris` Maven profile that pulls it right from there.

2025-01-02 17:04 UTC, bdeboe commented
Thanks for taking a look at this @anthonysena 

If you could please let me know where I can appropriately document how to get the drivers I'll do that right away.

Thanks & happy 2025!

2025-01-02 19:07 UTC, anthonysena commented on src/main/java/org/ohdsi/webapi/DataAccessConfig.java
> +        supportedDrivers = new String[]{"org.postgresql.Driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver", "oracle.jdbc.driver.OracleDriver", "com.amazon.redshift.jdbc.Driver", "com.cloudera.im
@bdeboe - a maven profile would be ideal. To document how to use it you can follow the example for some of the other db platforms such as: https://github.com/OHDSI/WebAPI/tree/master/src/main/extras/bigquery.

2025-01-03 07:46 UTC, bdeboe commented on src/main/java/org/ohdsi/webapi/DataAccessConfig.java
> +        supportedDrivers = new String[]{"org.postgresql.Driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver", "oracle.jdbc.driver.OracleDriver", "com.amazon.redshift.jdbc.Driver", "com.cloudera.im
Done. (see last two commits on this branch)

Please let me know if there's anything else you'd like us to add before this PR is eligible to be merged

2025-01-08 13:32 UTC, alex-odysseus commented
Benjamin, please create a pull request to the Atlas repository from your company repository https://github.com/intersystems-community/OHDSI-Atlas/commits/master/
Anthony, I think we are good to merge
@bdeboe @anthonysena

2025-01-28 07:50 UTC, bdeboe commented
Hi @anthonysena , I believe we addressed your questions, so hopefully this is now ready for acceptance?
Thanks!

2025-02-24 14:31 UTC, bdeboe commented
Hi @anthonysena,
any chance you can look into this? We're promoting the use of Atlas/WebAPI, including through BroadSea, and having this be part of the master repo would be a great help. 
Thanks in advance!
benjamin

2025-02-24 15:04 UTC, anthonysena approved these changes
Thanks @bdeboe these changes look good from my perspective. I know @chrisknoll is also going to review so we'll give him some time to take a look.

2025-02-25 16:35 UTC, merged